### ISSUE TITLE
app crash: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by drpo** [SecUSo/privacy-friendly-weather#182]
```
D raindrops: raininfo "000000000"
D AndroidRuntime: Shutting down VM
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.secuso.privacyfriendlyweather, PID: 32296
E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=9; index=9
E AndroidRuntime: 	at java.lang.String.charAt(Native Method)
E AndroidRuntime: 	at org.secuso.privacyfriendlyweather.ui.RecycleList.CityWeatherAdapter.setRainDrops(CityWeatherAdapter.java:838)
E AndroidRuntime: 	at org.secuso.privacyfriendlyweather.ui.RecycleList.CityWeatherAdapter.onBindViewHolder(CityWeatherAdapter.java:662)
E AndroidRuntime: 	at org.secuso.privacyfriendlyweather.ui.RecycleList.CityWeatherAdapter.onBindViewHolder(CityWeatherAdapter.java:43)
```

**Comment by sleep-yearning** [comment]
Thank you for the report. Looks like this is the same as #188 in origin. 
Please see comments there for a workaround/explanation for the moment.
