### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by kehugter** [SecUSo/privacy-friendly-weather#19]
I'm using
Custom CM11 ROM (based on Android 4.4.4)
Kernel 3.0
privacy-friendly-weather from F-Droid

The app crashes during the splash screen.

logcat
```text
I/Timeline(31437): Timeline: Activity_launch_request id:org.secuso.privacyfriendlyweather time:22404074
I/ActivityManager( 2190): START u0 {cmp=org.secuso.privacyfriendlyweather/.MainActivity} from pid 31437
I/libblt_hw( 1781): Library closed (handle = 5, fd = 63)
D/AndroidRuntime(31437): Shutting down VM
W/dalvikvm(31437): threadid=1: thread exiting with uncaught exception (group=0x2c60fce0)
E/AndroidRuntime(31437): FATAL EXCEPTION: main
E/AndroidRuntime(31437): Process: org.secuso.privacyfriendlyweather, PID: 31437
E/AndroidRuntime(31437): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.secuso.privacyfriendlyweather/org.secuso.privacyfriendlyweather.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
E/AndroidRuntime(31437): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime(31437): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime(31437): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(31437): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime(31437): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31437): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(31437): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(31437): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31437): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(31437): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(31437): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(31437): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(31437): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31437): Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
E/AndroidRuntime(31437): 	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:466)
E/AndroidRuntime(31437): 	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:320)
E/AndroidRuntime(31437): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:281)
E/AndroidRuntime(31437): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
E/AndroidRuntime(31437): 	at org.secuso.privacyfriendlyweather.MainActivity.onCreate(MainActivity.java:48)
E/AndroidRuntime(31437): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(31437): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(31437): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/AndroidRuntime(31437): 	... 12 more
W/ActivityManager( 2190):   Force finishing activity org.secuso.privacyfriendlyweather/.MainActivity
I/WindowManager( 2190): Screenshot max retries 4 of Token{2ca406d8 ActivityRecord{2d0fb600 u0 org.secuso.privacyfriendlyweather/.MainActivity t32 f}} appWin=Window{2d09d488 u0 Starting org.secuso.privacyfriendlyweather} drawState=4
W/WindowManager( 2190): Screenshot failure taking screenshot for (480x800) to layer 21055
```

**Comment by Yonjuni** [comment]
Thanks for the Stack Trace. The app requires Android 5.0 (API 21). We have already corrected it with the update to version 1.1
